---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverwork
description: Silverblue image based on BlueBuild's base images with CachyOS kernel
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  # Copy necessary system files
  - type: files
    files:
      - source: system
        destination: /

  # Minimal base image without extra GUI or CLI tools
  - type: dnf
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - nvtop
        - gnome-software
        - gnome-tour
        - ptyxis
        - gnome-system-monitor
        - malcontent-control
        - gnome-disk-utility
        - gnome-color-manager
        - yelp
        - pipewire-config-raop
        - gnome-shell-extension-background-logo
    install:
      skip-unavailable: true
      packages:
        - adw-gtk3-theme

  # Minimal set of apps to be able to install other apps
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
          - app.devsuite.Ptyxis
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.gtk.Gtk3theme.adw-gtk3
      - scope: user

  # AppIndicator and KStatusNotifierItem Support
  - type: gnome-extensions
    install:
      - 615 

  # CachyOS Addons
  - from-file: cachyos.yml

  # Services needed
  - type: systemd
    system:
      enabled:
        - podman.socket
        - flatpak-settings-firstboot.service
        - hostname-firstboot.service
        - mok-enroll-firstboot.service
        - scx_loader.service

  # Sign kernel and modules recursively
  - type: script
    env:
      CERT: /usr/share/silverwork/MOK.pem
      KEY: /tmp/certs/MOK.priv
    secrets:
      - type: file
        source: ./MOK.priv
        mount: 
          type: file
          destination: /tmp/certs/MOK.priv
    scripts:
      - sign.sh

  # Re-build initramfs
  - type: script
    scripts:
      - initramfs.sh

  # Set OS name
  - type: os-release
    properties:
      ID: silverwork
      ID_LIKE: fedora
      NAME: SilverWork
      PRETTY_NAME: SilverWork - Silverblue for Azerion HP ZBook G1A

  - type: signing
