name: silvercachy
description: Silverblue image based on BlueBuild's base images with CachyOS kernel and Nvidia
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: latest
modules:
  # Copy necessary system files
  - type: files
    files:
      - source: system
        destination: /

  # Most of these should be used through flatpaks
  - type: dnf
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - nvtop
        - dconf-editor
        - gnome-software
        - gnome-tour
        - gnome-terminal
        - ptyxis
        - gnome-system-monitor
        - malcontent-control
        - gnome-disk-utility
        - gnome-color-manager
        - yelp

  # Minimal set of apps to be able to install other apps
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
          - app.devsuite.Ptyxis
      - scope: user

  # Replace the Fedora kernel with the CachyOS
  - type: script
    scripts:
      - kernel.sh

  # Compile Nvidia module for CachyOS kernel and install userspace packages
  - type: script
    scripts:
      - nvidia.sh

  # Setup for Nvidia
  - type: kargs
    kargs:
      - rd.driver.blacklist=nouveau
      - modprobe.blacklist=nouveau
      - nvidia-drm.modeset=1
      - nvidia-drm.fbdev=1

  - type: script
    snippets:
      - cp /usr/lib/modprobe.d/nvidia-modeset.conf /etc/modprobe.d/nvidia-modeset.conf
      - sed -i 's/omit_drivers/force_drivers/g' /usr/lib/dracut/dracut.conf.d/99-nvidia.conf
      - sed -i 's/ nvidia / i915 amdgpu nvidia /g' /usr/lib/dracut/dracut.conf.d/99-nvidia.conf

  # Re-build initramfs
  - type: initramfs
    env:
      DRACUT_NO_XATTR: '1'

  - type: signing
